name: chatgpt_clone
description: A Flutter-based clone of the ChatGPT mobile application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted to a more current SDK range

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0 # For making API calls
  shared_preferences: ^2.2.0 # For local storage (still used by AuthService for API key)
  flutter_bloc: ^8.1.3 # For state management
  equatable: ^2.0.5 # For value equality in BLoC states/events
  sqflite: ^2.3.0 # For local database
  path_provider: ^2.1.1 # For finding paths to store database
  uuid: ^4.2.1 # For generating unique IDs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0 # Added BLoC testing utility
  mocktail: ^1.0.0 # Added mocking utility (using 1.0.0 as a common recent version)
  sqflite_common_ffi: ^2.3.0 # For in-memory DB testing

flutter:
  uses-material-design: true
