# platform :ios, '11.0'  # Or your target iOS version
# CocoaPodsيفترضالتالي بناءً على افتراضات Flutter.
# Read more about CocoaPods here: https://guides.cocoapods.org/using/getting-started.html#using-cocoapods

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
